import Navbar from "@/components/Navbar";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { styles } from "@/styles";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`bg-lightModeBg dark:bg-darkModeBg ${styles.nunito}`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
